#!/usr/bin/env zsh

SSH_HOST_PLUGIN_DIR="${0:A:h:h}"
source "${SSH_HOST_PLUGIN_DIR}/ssh-host.plugin.conf"
source "${SSH_HOST_PLUGIN_DIR}/utils/host.zsh"

_ssh_host_preview_form() {
    local host_alias="${1:- ...}"
    local hostname="${2:- ...}"
    local user="${3:- ...}"
    local port="${4:- ...}"
    local key_type="${5:- ...}"
    
    local config
    config=$(printf "hostname %s\nuser %s\nport %s\nkeytype %s\nidentitiesonly yes" "$hostname" "$user" "$port" "$key_type")
    
    _ssh_host_print_host_config "$host_alias" "$config"
}

[[ $# -gt 0 ]] && _ssh_host_preview_form "$@"
