#!/usr/bin/env zsh

SSH_HOST_PLUGIN_DIR="${0:A:h:h}"
source "${SSH_HOST_PLUGIN_DIR}/utils/fzf.zsh"

_ssh_host_main() {
    local hosts=$(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_list)

    [[ -z "$hosts" ]] && { "${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_add" add < /dev/tty > /dev/tty; return; }

    echo "$hosts" | _ssh_host_fzf_base \
            --ghost="Type to filter: " \
            --preview="${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_preview {1}" \
            --bind="esc:abort" \
            --bind="enter:become(ssh {1})" \
            --bind="ctrl-n:become(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_add add < /dev/tty > /dev/tty)+abort" \
            --bind="ctrl-e:execute(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_edit {1} desc < /dev/tty > /dev/tty)+reload(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_list)" \
            --bind="ctrl-p:execute-silent(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_edit {1} pinned < /dev/tty > /dev/tty)+reload(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_list)" \
            --bind="ctrl-u:become(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_scp {1} upload < /dev/tty > /dev/tty)" \
            --bind="ctrl-d:become(${SSH_HOST_PLUGIN_DIR}/src/_ssh_host_scp {1} download < /dev/tty > /dev/tty)" \
            --bind 'focus:+bg-transform-footer:
                    echo "[Enter] Connect  • [Esc] Quit"
                    echo "[Ctrl-N] Add New • [Ctrl-E] Edit • [Ctrl-P] Pin"
                    echo "[Ctrl-U / Ctrl-D] Upload/Download File"' \
            --preview-window=right:40%
}

[[ "${(%):-%x}" == "${0}" ]] && _ssh_host_main "$@"
