#!/usr/bin/env zsh

SSH_HOST_PLUGIN_DIR="${0:A:h:h}"
source "${SSH_HOST_PLUGIN_DIR}/ssh-host.plugin.conf"
source "${SSH_HOST_PLUGIN_DIR}/utils/host.zsh"

_ssh_host_preview_entry() {
    local host_alias="$1"
    [[ -z "$host_alias" ]] && return
    
    local config=$(_ssh_host_config_by_alias "$host_alias" "$SSH_HOST_PREVIEW_FIELDS")
    _ssh_host_print_host_config "$host_alias" "$config"
}

[[ $# -gt 0 ]] && _ssh_host_preview_entry "$@"
